---
title: "Example usage or rawTof"
author: "Clemens Ager"
date: "`r Sys.Date()`"
output: 
  rmarkdown:::html_vignette
vignette: >
  %\VignetteIndexEntry{Example Usage}
  %\VignetteKeyword{example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Example usage

This vignette shows how to load the sample PTR data provided by
Ionicon.

_Note: this will download a 45M file_
```{r}
tof_file <- file.path(tempdir(), "PTRTOF_test_spectrum.h5")
library(curl)
curl_download("https://dl.dropboxusercontent.com/s/c4miuh22ojswf5r/PTRTOF_test_spectrum.h5?dl=0#",
			  destfile=tof_file)
```

The package requires [rhdf5](https://bioconductor.org/packages/release/bioc/html/rhdf5.html).
```{r library}
library(rhdf5)
library(rawTof)
```

## Opening a TOF file

```{r opening a tof file}
fid <- H5Fopen(tof_file)
```

## Getting the peak data

```{r}
peaktable <- get_peak_matrix(fid)
plot(peaktable[69, ], type="l", ylab="m/z 69")
plot(peaktable[45, ], type="l", ylab="m/z 45")
```


## Getting individual scans and the sum spectrum


### obtaining the mass calibration

### getting the sum spectrum
```{r}
ss <- get_sum_spec(fid)/180
```

```{r}
s2 <- get_single_scan(fid, 31)
```

```{r}
mh <- masscal_helper(fid)
mass_scale <- mh$to_mass(seq_along(ss))
```

### Plotting

```{r}
plot(mass_scale, s2, type="l")
lines(mass_scale, ss, col="red")
```

#### extracting a mass range
```{r}
mass_range <- mh$to_index(c(40, 50))
selected <- seq(from = floor(mass_range[1]),
                to = ceiling(mass_range[2]))

plot(mass_scale[selected], s2[selected], type="l")
lines(mass_scale[selected], ss[selected], col="red")
```
